### ISSUE TITLE
SD_MODE pin connection to the Pinout

### ISSUE THREAD

**Issue by Sureshsepg** [pimoroni/speaker-phat#25]
Hi,
I have a question on the Pin out. Where is the SD_MODE pin of the DAC routed to the Pin out, is it the BCM21(I2S) pin or is it a different pin., I need to enable this pin separately for enabling the audio in Android-things running on Raspberry pi. As shown on this stack overflow thread [link](https://stackoverflow.com/questions/49161714/configuring-speaker-phat-with-androidthings-on-raspberrypi).
Thanks for your support in advance.

**Comment by Gadgetoid** [comment]
The `SD_MODE` pin is not broken out. It's, effectively, tied on since it's used, with accompanying circuitry, to enable the amp when the PCM frame-sync is detected. This prevents an issue on the Pi/Raspbian where, if I remember correctly, the PCM clock would be running without frame-sync or data which is a huge no-no for this amp, and basically turned it into a tiny heater.
